### PR TITLE
AWS Lambda support using Zappa

### LINKED ISSUE #57: Improve Security
Status: Yellow

Plans:
- [x] Get AWS Credit.
- [ ] Change CircleCI to deploy to AWS instead of Heroku.
- [x] Research AWS Lambda
- [ ] ~~(If using Docker)~~
  - [ ] ~~Setup docker image.~~
  - [ ] ~~Have a single user's requests direct to the same container and have a different container for each user.~~

References:
- https://github.com/christophetd/docker-python-sandbox
  - We would need to modify this so that each request does not create/destroy its own container.
- http://containertutorials.com/docker-compose/flask-simple-app.html
- https://djangostars.com/blog/what-is-docker-and-how-to-use-it-with-python/

### LINKED ISSUE #64: Add timeout

### LINKED ISSUE #73: Zappa support for AWS Lambda
- [x] Rename `app/app.py` -> `app/my_app.py` to support entry app function
- [x] Add Zappa configuration

### PR DESCRIPTION
**Pull request by jcruz**
- [x] Resolve #73 with Zappa support
- [x] Resolve #64 with 30 second timeout
- [x] Resolve #57 with serverless & containerized AWS Lambda
- [x] #1 Merged

### Security example
Output of running `os.system('ls -la')`

AWS EC2 Instance
screen shot 2018-03-24 at 11 32 35 am

AWS Lambda
screen shot 2018-03-24 at 11 31 50 am

### CODE REVIEW

**Comment by jcruz** [comment]
Unfortunately, our unit tests only test the flask app. On AWS Lambda, it's similar to executing code as an unprivileged user. Tests are run as a privileged user anyways so I don't think tests are needed in this case.

**Comment by nkadonaga** [comment]
Ok, got it. Sounds good!

**Comment by jcruz** [comment]
In zappa settings it needs a reference to the app. With our directory structure, we want `app` from `app/app.py`. This is `app.app.app` but it isn't recognized is because `app` is a package since its a directory.

**Comment by mjenrungrot** [comment]
@jcruz I think it's fine with my_app then.

**Pull request merged**
