### PR TITLE
compile and run coconut within python

### PR DESCRIPTION
**Pull request by jcruz**
Instead of writing a temporary file, use coconut's `parse` function and execute code.

- [x] Remove subprocess
- [x] Use Coconut's `parse` to compile
- [x] Use `exec` to run (safe on AWS Lambda)
- [x] Decreased file read/write latency (improved performance)
- [x] Unit tests passing

### CODE REVIEW

**Comment by jcruz** [comment]
Turns out this doesn't work on certain code. Will revisit later.

For example, I'm getting
```
name '_coconut' is not defined
```

on the following code
```
data Empty()
data Leaf(n)
data Node(l, r)

def size(Empty()) = 0

@addpattern(size)
def size(Leaf(n)) = 1

@addpattern(size)
def size(Node(l, r)) = size(l) + size(r)
```

**Comment by jcruz** [comment]
Reopening this old PR, we actually need this for AWS Lambda.

`name '_coconut' is not defined` fixed by adding the `sys` global to the exec environment.

**Comment by jcruz** [comment]
@nkadonaga How do I run the linter?

**Comment by nkadonaga** [comment]
`pylint app.py` doesn't actually fix things, but will return a list of errors/warnings 🎉

**Pull request merged**
